### ISSUE TITLE
Initialization LinAlgError

### ISSUE THREAD

**Issue by RomeshA** [atomicateam/atomica#318]
When loading the databook, the following error occurs

```
Traceback (most recent call last):

  File "<ipython-input-23-2b64a82813b5>", line 1, in <module>
    runfile('C:/Users/ER/Documents/GitHub/tb-ucl-analyses/indonesia/run_indonesia.py', wdir='C:/Users/ER/Documents/GitHub/tb-ucl-analyses/indonesia')

  File "D:\Software\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 704, in runfile
    execfile(filename, namespace)

  File "D:\Software\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 108, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/ER/Documents/GitHub/tb-ucl-analyses/indonesia/run_indonesia.py", line 69, in <module>
    P.load_databook(databook_path=databook_path, make_default_parset=True, do_run=True)

  File "C:\Users\ER\Documents\GitHub\atomica\atomica\project.py", line 209, in load_databook
    self.run_sim(parset="default", store_results=True)

  File "C:\Users\ER\Documents\GitHub\atomica\atomica\project.py", line 433, in run_sim
    program_instructions=progset_instructions, name=result_name)

  File "C:\Users\ER\Documents\GitHub\atomica\atomica\model.py", line 1519, in run_model
    m = Model(settings, framework, parset, progset, program_instructions)

  File "C:\Users\ER\Documents\GitHub\atomica\atomica\model.py", line 1014, in __init__
    self.build(settings, parset)

  File "C:\Users\ER\Documents\GitHub\atomica\atomica\model.py", line 1122, in build
    self.pops[-1].initialize_compartments(parset, self.framework, self.t[0])

  File "C:\Users\ER\Documents\GitHub\atomica\atomica\model.py", line 900, in initialize_compartments
    x = np.linalg.lstsq(A, b.ravel(), rcond=None)[0].reshape(-1, 1)

  File "D:\Software\Anaconda3\lib\site-packages\numpy\linalg\linalg.py", line 2125, in lstsq
    _assertNoEmpty2d(a, b)  # TODO: relax this constraint

  File "D:\Software\Anaconda3\lib\site-packages\numpy\linalg\linalg.py", line 229, in _assertNoEmpty2d
    raise LinAlgError("Arrays cannot be empty")

LinAlgError: Arrays cannot be empty
```

**Comment by RomeshA** [comment]
This probably occurs for frameworks where some compartments don't appear in the initialization (because they are assumed to be empty). Older versions of `numpy` raise this error - confirmed to happen on 1.15.4.
This can be fixed by updating to the latest version of `numpy` - should be fine on 1.16.2 or later
