### ISSUE TITLE
Number parameters that aren't transition parameters can't be targeted

### ISSUE THREAD

**Issue by RomeshA** [atomicateam/atomica#320]
If a program targets a parameter in number units that isn't a transition parameter, the following error occurs

```
Traceback (most recent call last):

  File "<ipython-input-4-7d73916e6e27>", line 1, in <module>
    runfile('D:/GitHub/tb-ucl-analyses/indonesia/run_indonesia.py', wdir='D:/GitHub/tb-ucl-analyses/indonesia')

  File "D:\Software\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 786, in runfile
    execfile(filename, namespace)

  File "D:\Software\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "D:/GitHub/tb-ucl-analyses/indonesia/run_indonesia.py", line 64, in <module>
    F = at.ProjectFramework(framework_path)

  File "D:\GitHub\atomica\atomica\framework.py", line 88, in __init__
    self._validate()

  File "D:\GitHub\atomica\atomica\framework.py", line 753, in _validate
    raise InvalidFramework('Parameter "%s" is targetable and in number units, but is not a transition parameter. To target a parameter with programs in number units, the parameter must appear in the transition matrix.' % par.name)

InvalidFramework: Parameter "pd_ndiag" is targetable and in number units, but is not a transition parameter. To target a parameter with programs in number units, the parameter must appear in the transition matrix.
```

**Comment by RomeshA** [comment]
This error is raised because a conversion needs to take place between the program's fractional coverage, and the number outcome. In that case, the program's outcome should be entered as 'fraction per person' (e.g. treatment success rate) and then internally the outcome is multiplied by the number of people eligible for the transition, as determined by the number of people eligible for the transition governed by that parameter. If the parameter is not a transition parameter, then this number of people is undefined, so it is not possible to perform the conversion. See https://docs.atomica.tools/en/master/general/programs/Programs.html#parameters-in-number-units for further details
